apiVersion: apps/v1
kind: Deployment
metadata:
  name: geol-recap-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geol-recap-api
  template:
    metadata:
      labels:
        app: geol-recap-api
    spec:
      containers:
      - name: geol-recap-api
        image: mossnana/geol-recap-api:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3443

---
apiVersion: v1
kind: Service
metadata:
  name: geol-recap-api
  labels:
    app: geol-recap-api
spec:
  ports:
  - port: 80
    targetPort: 3443
    protocol: TCP
    name: http
  selector:
    app: geol-recap-api

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: geol-recap-api
  name: geol-recap-api
spec:
  backend:
    serviceName: geol-recap-api
    servicePort: 80
  rules:
  - host: mossnana.com
    http:
      paths:
      - path: /
        backend:
          serviceName: geol-recap-api
          servicePort: 80
